[workspace]
resolver = "2"
members = [
    "base64ct",
    "const-oid",
    "der",
    "der/derive",
    "pem-rfc7468",
    "pkcs1",
    "pkcs5",
    "pkcs7",
    "pkcs8",
    "pkcs12",
    "sec1",
    "spki",
    "x509"
]
